//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteCrud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Pessoa
    {
        public int Codigo { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public int Idade { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Apenas data")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<DateTime> Nascimento { get; set; }
        public bool Ativo { get; set; }
        [NotMapped]
        public virtual String FaixaEtaria
        {
            get
            {
                string retorno = "";
                if (Idade >= 0){
                    string numero = Idade.ToString();

                    retorno = numero.Length>1?numero.Substring(0, numero.Length - 1):"";
                    retorno = retorno + "0" + " - " + retorno + "9";

                }
                return retorno;
            }
        }
    }
}
